# On stocke les données mais on désactive le fichier de log problématique
persistence true
persistence_location /mosquitto/data/

# On envoie les logs directement dans la console Docker (pas dans un fichier)
log_dest stdout

# Port standard pour l'ESP32
listener 1883
allow_anonymous true

# Port WebSocket pour React
listener 9001
protocol websockets
allow_anonymous true
